### ISSUE TITLE
cannot install amd GPU driver(fglrx) 

### ISSUE THREAD

**Issue by VonWebEinstein** [cdeterman/gpuR#59]
I cannot install fglrx via
`sudo apt-get install fglrx-updates`
and the system carshed after  driver from AMD site ,
I tried Ubuntu 16.04 , 14.04.5,  14.04.4,
so I want to ask your system version?   @cdeterman

Many thanks!

**Comment by znmeb** [comment]
@VonWebEinstein @cdeterman The fglrx drivers are no longer supported on "modern" Linux distros. The open source drivers that ship with Ubuntu 16.04 should work with gpuR - at least, they did a few months ago when I was testing them.

The fglrx drivers probably still work on Ubuntu 14.04, but I think the new ones are better, and 16.04 has a much better desktop.

**Comment by VonWebEinstein** [comment]
@znmeb When I test them with 16.04, an error occurred:

`/usr/bin/ld: 找不到 -lOpenCL
collect2: error: ld returned 1 exit status
/usr/share/R/share/make/shlib.mk:6: recipe for target 'gpuR.so' failed
make: *** [gpuR.so] Error 1
ERROR: compilation failed for package ‘gpuR’`

Need I install the GPU driver  manually?

**Comment by cdeterman** [comment]
@VonWebEinstein it is true as @znmeb states regarding newer Debian machines.  I had however made a mistake in the `configure` file that detects whether an `OpenCL` library is available on your machine.  It  should now detect that no OpenCL is available and build the internal ICD.  Then, if you have the appropriate driver for your particular device then all should work fine.  Do you have an AMD GPU like a FirePro or something?

**Comment by VonWebEinstein** [comment]
Finally, I achieved.
The error comes from the configuration of AMDAPPSDK, not the GPU driver.
*/opt/AMDAPPSDK-3.0/lib/x86_64/libOpenCL.so*  is a Symbolic Link, reference to a file which doesn't exist. So I remove it and made a new one via
`cd /opt/AMDAPPSDK-3.0/lib/x86_64`
`sudo rm libOpenCL.so`
`sudo ln -s sdk/libOpenCL.so.1 libOpenCL.so`

Thanks very much. @znmeb @cdeterman
